structurizr:
  workspace:
    name: "Coding Contest Platform"
    description: ""
  export:
    structurizr:
      enabled: false
      id: -1
      key: "enter key here"
      secret: "enter secret here"
    c4-plant-uml:
      enabled: true